// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: event/v1/model.proto

package eventpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Event with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Event) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Event with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in EventMultiError, or nil if none found.
func (m *Event) ValidateAll() error {
	return m.validate(true)
}

func (m *Event) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofTypePresent := false
	switch v := m.Type.(type) {
	case *Event_Test:
		if v == nil {
			err := EventValidationError{
				field:  "Type",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofTypePresent = true

		if all {
			switch v := interface{}(m.GetTest()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, EventValidationError{
						field:  "Test",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, EventValidationError{
						field:  "Test",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTest()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return EventValidationError{
					field:  "Test",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofTypePresent {
		err := EventValidationError{
			field:  "Type",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return EventMultiError(errors)
	}

	return nil
}

// EventMultiError is an error wrapping multiple validation errors returned by
// Event.ValidateAll() if the designated constraints aren't met.
type EventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EventMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EventMultiError) AllErrors() []error { return m }

// EventValidationError is the validation error returned by Event.Validate if
// the designated constraints aren't met.
type EventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EventValidationError) ErrorName() string { return "EventValidationError" }

// Error satisfies the builtin error interface
func (e EventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EventValidationError{}

// Validate checks the field values on EventBatch with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EventBatch) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EventBatch with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EventBatchMultiError, or
// nil if none found.
func (m *EventBatch) ValidateAll() error {
	return m.validate(true)
}

func (m *EventBatch) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := len(m.GetEvents()); l < 1 || l > 1024 {
		err := EventBatchValidationError{
			field:  "Events",
			reason: "value must contain between 1 and 1024 items, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetEvents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, EventBatchValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, EventBatchValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return EventBatchValidationError{
					field:  fmt.Sprintf("Events[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return EventBatchMultiError(errors)
	}

	return nil
}

// EventBatchMultiError is an error wrapping multiple validation errors
// returned by EventBatch.ValidateAll() if the designated constraints aren't met.
type EventBatchMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EventBatchMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EventBatchMultiError) AllErrors() []error { return m }

// EventBatchValidationError is the validation error returned by
// EventBatch.Validate if the designated constraints aren't met.
type EventBatchValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EventBatchValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EventBatchValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EventBatchValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EventBatchValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EventBatchValidationError) ErrorName() string { return "EventBatchValidationError" }

// Error satisfies the builtin error interface
func (e EventBatchValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEventBatch.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EventBatchValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EventBatchValidationError{}

// Validate checks the field values on UserEvent with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserEventMultiError, or nil
// if none found.
func (m *UserEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *UserEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() == nil {
		err := UserEventValidationError{
			field:  "UserId",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetUserId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserEventValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserEventValidationError{
					field:  "UserId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserEventValidationError{
				field:  "UserId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetEvent() == nil {
		err := UserEventValidationError{
			field:  "Event",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetEvent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserEventValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserEventValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEvent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserEventValidationError{
				field:  "Event",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UserEventMultiError(errors)
	}

	return nil
}

// UserEventMultiError is an error wrapping multiple validation errors returned
// by UserEvent.ValidateAll() if the designated constraints aren't met.
type UserEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserEventMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserEventMultiError) AllErrors() []error { return m }

// UserEventValidationError is the validation error returned by
// UserEvent.Validate if the designated constraints aren't met.
type UserEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserEventValidationError) ErrorName() string { return "UserEventValidationError" }

// Error satisfies the builtin error interface
func (e UserEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserEventValidationError{}

// Validate checks the field values on UserEventBatch with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserEventBatch) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserEventBatch with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserEventBatchMultiError,
// or nil if none found.
func (m *UserEventBatch) ValidateAll() error {
	return m.validate(true)
}

func (m *UserEventBatch) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := len(m.GetEvents()); l < 1 || l > 1024 {
		err := UserEventBatchValidationError{
			field:  "Events",
			reason: "value must contain between 1 and 1024 items, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetEvents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserEventBatchValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserEventBatchValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserEventBatchValidationError{
					field:  fmt.Sprintf("Events[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return UserEventBatchMultiError(errors)
	}

	return nil
}

// UserEventBatchMultiError is an error wrapping multiple validation errors
// returned by UserEventBatch.ValidateAll() if the designated constraints
// aren't met.
type UserEventBatchMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserEventBatchMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserEventBatchMultiError) AllErrors() []error { return m }

// UserEventBatchValidationError is the validation error returned by
// UserEventBatch.Validate if the designated constraints aren't met.
type UserEventBatchValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserEventBatchValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserEventBatchValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserEventBatchValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserEventBatchValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserEventBatchValidationError) ErrorName() string { return "UserEventBatchValidationError" }

// Error satisfies the builtin error interface
func (e UserEventBatchValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserEventBatch.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserEventBatchValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserEventBatchValidationError{}

// Validate checks the field values on Event_TestEvent with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *Event_TestEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Event_TestEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Event_TestEventMultiError, or nil if none found.
func (m *Event_TestEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *Event_TestEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetSourceAddress()); l < 1 || l > 256 {
		err := Event_TestEventValidationError{
			field:  "SourceAddress",
			reason: "value length must be between 1 and 256 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Nonce

	if len(errors) > 0 {
		return Event_TestEventMultiError(errors)
	}

	return nil
}

// Event_TestEventMultiError is an error wrapping multiple validation errors
// returned by Event_TestEvent.ValidateAll() if the designated constraints
// aren't met.
type Event_TestEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Event_TestEventMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Event_TestEventMultiError) AllErrors() []error { return m }

// Event_TestEventValidationError is the validation error returned by
// Event_TestEvent.Validate if the designated constraints aren't met.
type Event_TestEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Event_TestEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Event_TestEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Event_TestEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Event_TestEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Event_TestEventValidationError) ErrorName() string { return "Event_TestEventValidationError" }

// Error satisfies the builtin error interface
func (e Event_TestEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEvent_TestEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Event_TestEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Event_TestEventValidationError{}
